#!/bin/sh

echo "Content-type:text/html"
echo "<?xml version="1.0" encoding="UTF-8"?>"
echo "Start Send Message......<br><br>"
echo ""
#检测文件是否存在
#FILE="/mnt/sd01/DVR/test.file"
FILE="/tmp/FIFOTEST"
if [ -p ${FILE} ]
then
    echo "<FIFO>ok</FIFO><br>"
   # echo "file is exist <br>"
else
    mkfifo --m=0777 ${FILE}
    chmod 0777 ${FILE}
    echo "crete file......<br>"
fi
echo ""
#向文件中写入数据
TIME=`date +%s`
CMD="__LOCK_CURR_VIDEO__"
MSG=""$TIME""$CMD""
echo $MSG > ${FILE}
echo ""
#sleep 0.5
echo "Write Messge to FIFO OK<br> <br>"
/bin/date
echo ""

