
TEST_SRC=2-0_float.c  2-1_hydrone.c 2-2_char.c 2-3_enum.c  2-4_const.c  2-5_var.c
TEST=2-0_float 2-1_hydrone 2-2_char 2-3_enum 2-4_const 2-5_var
ALL=$(TEST)
CFLAGS= -g -Wall

all: $(ALL)

touch:
	touch $(TEST_SRC)


clean:
	$(RM) a.out $(TEST)

