
ALL:hello

hello:
	$(CC) -g -Wall hello.c -o hello

hello0:
	gcc hello.c -I~/pub_work/11-Proj/fly_work/01-CLanguageProgrammingOfEmbeddedLinux/00-hello -o hello
#-I<dir>选项可以在头文件的搜索路径列表中添加<dir>目录，GCC就会到指定的目录去查找相应的头文

clean:
	$(RM) a.out hello

