.PHONY:clean

AllObj	:=_enumT0 _define0 _define1 atoi_1

#0
_enumT0:_enumT0.c
	$(CC) -o _enumT0 -g -Wall _enumT0.c

#1
_define0:_define0.c
	$(CC) -o _define0 -g -Wall _define0.c

#2
_define1:_define1.c
	$(CC) -o _define1 -g -Wall _define1.c

#3
atoi_1:atoi_1.c
	$(CC) -o atoi_1 -g -Wall atoi_1.c

#4
itoa:itoa.c
	$(CC) -o itoa -g -Wall itoa.c

ALL:$(AllObj)

INSTALL:
	

clean:
	$(RM) $(AllObj) a.out
