
APP=sizeof printf scanf test_1

ALL:$(APP)

sizeof:
	$(CC) -g -Wall 01-sizeof.c -o sizeof

printf:
	$(CC) -g -Wall 01-printf.c -o printf

scanf:
	$(CC) -g -Wall 01-scanf.c -o scanf

test_1:
	$(CC) -g -Wall 01-test_1.c -o test_1

clean:
	$(RM) a.out  $(APP)
