#!/bin/bash

# first
# This file looks throught all the files in current directory 
# for the string $string ,and then prints the name of those 
# files to standard output .

string="wifi"
for file in *
do
	if grep -l $string $file
	then
		echo $file"123"
	fi
done

exit 0
